### ISSUE TITLE
Unable to instanciate Symfony\Component\HttpFoundation\File\File

### ISSUE THREAD

**Issue by ProPheT777** [doctrine/instantiator#22]
Hey, 

Currently i'm unable to test (via instanciator) File object or any object that extends this class because Instanciator failed :(

Given error : 

```
Could not produce an instance of "Domain\Mail\Attachment" via un-serialization, since an error was triggered in file "vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php" at line "184" (Doctrine\Instantiator\Exception\UnexpectedValueException)
```

Have you an idea, how deal with object containing a `Resource` ?

**Comment by Ocramius** [comment]
@ProPheT777 I need the previous exception in order to provide support for this.

**Comment by ProPheT777** [comment]
```
 exception 'Exception' with message 'unserialize(): Error at offset 60 of 61 bytes' in vendor/doctrine/instantiator/src/Doctrine/Instantiator/Exception/UnexpectedValueException.php:76
      Stack trace:
      #0 vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php(161): Doctrine\Instantiator\Exception\UnexpectedValueException::fromUncleanUnSerialization(Object(ReflectionClass), 'unserialize(): ...', 8, '/site/mailer.ev...', 185)
      #1 [internal function]: Doctrine\Instantiator\Instantiator->Doctrine\Instantiator\{closure}(8, 'unserialize(): ...', '/site/mailer.ev...', 185, Array)
      #2 vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php(185): unserialize('O:49:"Domain\\M...')
      #3 vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php(164): Doctrine\Instantiator\Instantiator->attemptInstantiationViaUnSerialization(Object(ReflectionClass), 'O:49:"Domain\\M...')
      #4 vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php(115): Doctrine\Instantiator\Instantiator->checkIfUnSerializationIsSupported(Object(ReflectionClass), 'O:49:"Evaneos\\M...')
      #5 vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php(80): Doctrine\Instantiator\Instantiator->buildFactory('Domain\\Mail\\...')
      #6 vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php(68): Doctrine\Instantiator\Instantiator->buildAndCacheFromFactory('Domain\\Mail\\...')
      #7 vendor/jms/serializer/src/JMS/Serializer/Construction/UnserializeObjectConstructor.php(33): Doctrine\Instantiator\Instantiator->instantiate('Domain\\Mail\\...')
```

**Comment by Ocramius** [comment]
Do you have a sample of `Domain\Mail\Attachment`? Does it by chance extend an internal PHP class?

**Comment by Ocramius** [comment]
Also: what PHP version is being used?

**Comment by ProPheT777** [comment]
yes sure,

```php
<?php

namespace Domain\Mail\Attachment;

use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

class Attachment extends File
{

}
```

And i'm using `PHP 5.5.29`

**Comment by Ocramius** [comment]
Yes, `File` extends `SplFileInfo`, which is an internal class.

PHP explicitly broke compatibility here, disallowing this sort of operation for internal classes: you will have to upgrade to either PHP 5.6 or PHP 7 in order to have this working, sorry.

**Comment by ProPheT777** [comment]
Ok nice to know, thank you !
